# LLMs

langchain_chat_kwargs = {
    "temperature": 0,
    "max_tokens": 4000,
    "verbose": True,
}
chat_openai_model_kwargs = {
    "top_p": 1.0,
    "frequency_penalty": 0.0,
    "presence_penalty": -1,
}

# Database constants
ANGGOTA_COLUMNS = [
    "uuid",
    "captured_at",
    "anggota_id",
    "nopes",
    "nuptk",
    "nuks",
    "email_login",
    "nama_gtk",
    "foto_ptk",
    "asal_sekolah",
    "status_satminkal",
    "nama_komunitas",
    "no_sk",
    "tgl_sk",
    "tipe_komunitas",
    "mapel_ukg",
    "jenjang",
    "nopes_ketua",
    "nama_ketua",
    "alamat",
    "kecamatan",
    "kota",
    "provinsi",
    "komunitas_id",
    "is_negeri",
    "status_anggota",
    "jabatan_komunitas",
    "kelamin",
    "umur",
    "simpkb_email",
    "simpkb_no_hp",
    "dapodik_email",
    "dapodik_no_hp",
    "mapel_ukg_ptk",
    "tugas",
    "jenis_ptk",
    "kualifikasi",
    "pegawai",
    "golongan",
    "alamat_sekolah",
    "dapodik_ptk_id",
    "longitude",
    "latitude",
    "no_kk",
    "nik",
    "nip",
    "dapodik_no_hp_operator",
    "nama_ibu_kandung",
    "npwp",
    "nama_npwp",
    "domisili_alamat_jalan",
    "domisili_nama_dusun",
    "domisili_kode_pos",
    "domisili_rt",
    "domisili_rw",
    "domisili_desa_kelurahan",
    "domisili_kecamatan",
    "domisili_kota_kabupaten",
    "domisili_provinsi",
    "status_keaktifan",
    "agama",
    "status_perkawinan",
    "kewarganegaraan",
    "niy_nigk",
    "npsn",
    "sekolah_id",
    "instansi_id",
    "dapodik_sekolah_id",
    "is_aktif_sekolah",
    "is_aktif",
    "nrg",
    "thn_sertifikasi",
    "mapel_sertifikasi",
    "last_access",
    "status_aktif",
    "status_sinkron",
    "jenis_ptk_kelompok",
    "mapel_ajar_dapodik",
    "k_kota",
    "instansi_tugas",
    "instansi_npsn_tugas",
    "paspor_id",
    "bentuk_pendidikan",
    "sumber_data",
    "kota_status_3t",
    "jenis_keluar",
    "tmp_lahir",
    "tgl_lahir",
    "status_aktif_sekolah",
    "sektor_vokasi",
    "naungan",
    "sekolah_akreditasi",
    "lembaga_akreditasi",
    "tahun_terdaftar",
    "asal_sekolah_jenis_naungan",
    "asal_sekolah_naungan",
    "status_sertifikasi",
    "status_nuptk"
]